In [5]:
# -*- coding: utf-8 -*-
"""historical_data_in_simple_table_for_n_years.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RJSU82yAjVUV06cGK7IchzBvXZ3Bk1yc
"""

import requests
import pandas as pd
from datetime import datetime, timedelta
# df=pd.read_csv('/content/ind_nifty50list.csv')
df=pd.read_csv('/content/complete.csv')
df

import requests
import pandas as pd
from datetime import datetime, timedelta

# Function to fetch historical data for a given time period
def fetch_historical_data(symbol, start_date, end_date):
    url = f'https://api.upstox.com/v2/historical-candle/{symbol}/1minute/{end_date}/{start_date}'
    headers = {'Accept': 'application/json'}
    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        data = response.json().get('data', [])
        return pd.DataFrame(data)
    else:
        print(f"Error: {response.status_code} - {response.text}")
        return None

# Function to fetch instrument_keys based on a list of names using boolean indexing
def get_instrument_keys(df, names):
    instrument_keys = {}

    for name in names:
        mask = df['tradingsymbol'] == name
        if mask.any():
            instrument_key = df.loc[mask, 'instrument_key'].iloc[0]
            instrument_keys[name.lower()] = instrument_key
        else:
            print(f"No instrument_key found for name: {name}")

    return instrument_keys

# Example usage for multiple names
names_to_search = ['RELIANCE', 'TATASTEEL', 'INFY']
instrument_keys_result = get_instrument_keys(df, names_to_search)

# Specify the number of years to fetch historical data
num_years = 27

# Dictionary to store DataFrames
dfs = {}

# Loop through each instrument key and fetch historical data
for name, instrument_key in instrument_keys_result.items():
    if instrument_key is not None:
        df_symbol = pd.DataFrame()

        for i in range(num_years):
            end_date = (datetime.today() - timedelta(days=365 * i)).strftime('%Y-%m-%d')
            start_date = (datetime.today() - timedelta(days=365 * (i + 1))).strftime('%Y-%m-%d')

            # Fetch historical data for the current time period
            df_current_period = fetch_historical_data(instrument_key, start_date, end_date)

            # Append the data to the df_symbol DataFrame
            if df_current_period is not None:
                df_symbol = pd.concat([df_symbol, df_current_period], ignore_index=True)

        # Convert timestamp column to datetime format
        if 'timestamp' in df_symbol.columns:
            df_symbol['timestamp'] = pd.to_datetime(df_symbol['timestamp'])

        # Store the DataFrame in the dictionary with a name like df_reliance
        dfs[f"df_{name.lower()}"] = df_symbol

# Access individual DataFrames using dfs dictionary
df_reliance = dfs.get('df_reliance', pd.DataFrame())
df_tatasteel = dfs.get('df_tatasteel', pd.DataFrame())
df_infy = dfs.get('df_infy', pd.DataFrame())

# Print individual DataFrames
print("DataFrame for RELIANCE:")
print(df_reliance)

print("\nDataFrame for TATASTEEL:")
print(df_tatasteel)

print("\nDataFrame for INFY:")
print(df_infy)

import pandas as pd

# Function to clean the data for a given DataFrame
def clean_data(df):
    # Create an empty DataFrame with the desired column names
    columns = ['timestamp', 'open', 'high', 'low', 'close', 'volume', 'open interest']
    df_cleaned_data = pd.DataFrame(columns=columns)

    # Iterate through each row in the original DataFrame
    for index, row in df.iterrows():
        # Extract data from the list
        row_data = row[0] if isinstance(row[0], list) else row[0][0]  # Assuming each row contains a list or list within a list

        # Reshape the row_data if needed
        if isinstance(row_data, list) and len(row_data) == 1:
            row_data = row_data[0]

        # Create a temporary DataFrame
        temp_df = pd.DataFrame([row_data], columns=columns[:len(row_data)])

        # Append the temporary DataFrame to the cleaned DataFrame
        df_cleaned_data = pd.concat([df_cleaned_data, temp_df], ignore_index=True)

    # Convert timestamp column to datetime format
    df_cleaned_data['timestamp'] = pd.to_datetime(df_cleaned_data['timestamp'])

    return df_cleaned_data

# Example usage for each DataFrame
df_reliance_cleaned = clean_data(df_reliance)
df_tatasteel_cleaned = clean_data(df_tatasteel)
df_infy_cleaned = clean_data(df_infy)

# Print cleaned DataFrames
print("Cleaned DataFrame for RELIANCE:")
print(df_reliance_cleaned)

print("\nCleaned DataFrame for TATASTEEL:")
print(df_tatasteel_cleaned)

print("\nCleaned DataFrame for INFY:")
print(df_infy_cleaned)

# # Calculate the difference between 'high' and 'low' and store it in a new column
# df_cleaned_data['ideal_change_%'] = ((df_cleaned_data['high'] - df_cleaned_data['low'])/(df_cleaned_data['high']+df_cleaned_data['low']))*200
# df_cleaned_data['ideal_change_%']

# import matplotlib.pyplot as plt
# import seaborn as sns
# # # Filter columns with more than 10 unique numeric values
# # numeric_cols = df.select_dtypes(include='number')
# # cols_to_plot = numeric_cols.columns[numeric_cols.nunique() > 2]

# # # Plot histograms and PDFs for selected columns
# # for column in cols_to_plot:
# plt.figure(figsize=(8, 4))
# # Plot histogram
# plt.subplot(1, 2, 1)
# sns.histplot(df_cleaned_data['ideal_change_%'], kde=False, bins=50)
# plt.title(f'Histogram for ideal_change_%')

# # Plot PDF
# plt.subplot(1, 2, 2)
# sns.histplot(df_cleaned_data['ideal_change_%'], kde=True, bins=50, color='orange')
# plt.title(f'PDF for column')
# #print(df[column].skew())

# plt.tight_layout()
# plt.show()

DataFrame for RELIANCE:
                                                 candles
0      [2024-02-02T15:29:00+05:30, 2912.85, 2913, 290...
1      [2024-02-02T15:28:00+05:30, 2913.5, 2914.2, 29...
2      [2024-02-02T15:27:00+05:30, 2912.65, 2914.55, ...
3      [2024-02-02T15:26:00+05:30, 2912.9, 2913.75, 2...
4      [2024-02-02T15:25:00+05:30, 2913.95, 2914, 291...
...                                                  ...
47677  [2023-07-31T09:19:00+05:30, 2526.75, 2526.9, 2...
47678  [2023-07-31T09:18:00+05:30, 2527.85, 2530, 252...
47679  [2023-07-31T09:17:00+05:30, 2531.05, 2532, 252...
47680  [2023-07-31T09:16:00+05:30, 2532.6, 2536.1, 25...
47681  [2023-07-31T09:15:00+05:30, 2528.65, 2532.3, 2...

[47682 rows x 1 columns]

DataFrame for TATASTEEL:
                                                 candles
0      [2024-02-02T15:29:00+05:30, 138.7, 138.85, 138...
1      [2024-02-02T15:28:00+05:30, 138.65, 138.8, 138...
2      [2024-02-02T15:27:00+05:30, 138.65, 138.75, 13...
3      [2024-02-02T15:26:00+05:30, 138.65, 138.7, 138...
4      [2024-02-02T15:25:00+05:30, 138.7, 138.7, 138....
...                                                  ...
47677  [2023-07-31T09:19:00+05:30, 121.25, 121.35, 12...
47678  [2023-07-31T09:18:00+05:30, 121.3, 121.35, 121...
47679  [2023-07-31T09:17:00+05:30, 121.3, 121.3, 121....
47680  [2023-07-31T09:16:00+05:30, 121.2, 121.4, 121....
47681  [2023-07-31T09:15:00+05:30, 120.65, 121.1, 120...

[47682 rows x 1 columns]

DataFrame for INFY:
                                                 candles
0      [2024-02-02T15:29:00+05:30, 1692.95, 1693.8, 1...
1      [2024-02-02T15:28:00+05:30, 1693.5, 1694, 1691...
2      [2024-02-02T15:27:00+05:30, 1693.4, 1694.75, 1...
3      [2024-02-02T15:26:00+05:30, 1693, 1693.6, 1692...
4      [2024-02-02T15:25:00+05:30, 1693, 1693.45, 169...
...                                                  ...
47677  [2023-07-31T09:19:00+05:30, 1339.7, 1340.95, 1...
47678  [2023-07-31T09:18:00+05:30, 1336, 1339.7, 1335...
47679  [2023-07-31T09:17:00+05:30, 1336.05, 1336.8, 1...
47680  [2023-07-31T09:16:00+05:30, 1333.85, 1336.35, ...
47681  [2023-07-31T09:15:00+05:30, 1348.7, 1348.7, 13...

[47682 rows x 1 columns]
Cleaned DataFrame for RELIANCE:
                      timestamp     open     high      low    close volume  \
0     2024-02-02 15:29:00+05:30  2912.85     2913  2908.05     2913   9603
1     2024-02-02 15:28:00+05:30  2913.50   2914.2  2912.05  2912.85  20969
2     2024-02-02 15:27:00+05:30  2912.65  2914.55  2912.05   2913.5  26674
3     2024-02-02 15:26:00+05:30  2912.90  2913.75  2912.05  2912.75  25601
4     2024-02-02 15:25:00+05:30  2913.95     2914  2910.40  2912.85  35206
...                         ...      ...      ...      ...      ...    ...
47677 2023-07-31 09:19:00+05:30  2526.75   2526.9  2521.50  2522.25  23841
47678 2023-07-31 09:18:00+05:30  2527.85     2530  2526.75  2526.75  23394
47679 2023-07-31 09:17:00+05:30  2531.05     2532  2527.00   2527.9  47933
47680 2023-07-31 09:16:00+05:30  2532.60   2536.1  2532.00  2532.15  44387
47681 2023-07-31 09:15:00+05:30  2528.65   2532.3  2528.50     2532  64758

      open interest
0                 0
1                 0
2                 0
3                 0
4                 0
...             ...
47677             0
47678             0
47679             0
47680             0
47681             0

[47682 rows x 7 columns]

Cleaned DataFrame for TATASTEEL:
                      timestamp    open    high     low   close  volume  \
0     2024-02-02 15:29:00+05:30  138.70  138.85  138.55  138.60  194220
1     2024-02-02 15:28:00+05:30  138.65  138.80  138.60  138.70  374886
2     2024-02-02 15:27:00+05:30  138.65  138.75  138.55  138.70  192490
3     2024-02-02 15:26:00+05:30  138.65  138.70  138.60  138.65  149381
4     2024-02-02 15:25:00+05:30  138.70  138.70  138.60  138.60  161492
...                         ...     ...     ...     ...     ...     ...
47677 2023-07-31 09:19:00+05:30  121.25  121.35  121.25  121.30  129658
47678 2023-07-31 09:18:00+05:30  121.30  121.35  121.25  121.30  206271
47679 2023-07-31 09:17:00+05:30  121.30  121.30  121.10  121.30  195471
47680 2023-07-31 09:16:00+05:30  121.20  121.40  121.05  121.35  301359
47681 2023-07-31 09:15:00+05:30  120.65  121.10  120.60  120.95  346715

      open interest
0                 0
1                 0
2                 0
3                 0
4                 0
...             ...
47677             0
47678             0
47679             0
47680             0
47681             0

[47682 rows x 7 columns]

Cleaned DataFrame for INFY:
                      timestamp     open     high      low    close  volume  \
0     2024-02-02 15:29:00+05:30  1692.95  1693.80  1691.60  1693.30    6660
1     2024-02-02 15:28:00+05:30  1693.50  1694.00  1691.40  1691.95   25048
2     2024-02-02 15:27:00+05:30  1693.40  1694.75  1693.00  1693.65   32813
3     2024-02-02 15:26:00+05:30  1693.00  1693.60  1692.65  1693.40   29068
4     2024-02-02 15:25:00+05:30  1693.00  1693.45  1690.00  1692.85   43336
...                         ...      ...      ...      ...      ...     ...
47677 2023-07-31 09:19:00+05:30  1339.70  1340.95  1338.20  1340.95   40564
47678 2023-07-31 09:18:00+05:30  1336.00  1339.70  1335.80  1339.30   58189
47679 2023-07-31 09:17:00+05:30  1336.05  1336.80  1334.10  1336.05   63930
47680 2023-07-31 09:16:00+05:30  1333.85  1336.35  1333.75  1336.15   86692
47681 2023-07-31 09:15:00+05:30  1348.70  1348.70  1333.85  1333.85  206287

      open interest
0                 0
1                 0
2                 0
3                 0
4                 0
...             ...
47677             0
47678             0
47679             0
47680             0
47681             0

[47682 rows x 7 columns]

In [7]:
import pandas as pd
from datetime import datetime

# Assuming you have already defined and cleaned your DataFrames: df_reliance_cleaned, df_tatasteel_cleaned, df_infy_cleaned

# Function to save DataFrame to Excel with a specific file name
def save_to_excel(df, df_name):
    # Remove timezone information from datetime columns
    df_no_timezone = df.copy()
    df_no_timezone['timestamp'] = df_no_timezone['timestamp'].dt.tz_localize(None)

    file_name = f"{df_name}_historical_1minute_data.xlsx"
    df_no_timezone.to_excel(file_name, index=False)
    print(f"DataFrame '{df_name}' successfully saved to Excel file: {file_name}")

# Save each DataFrame to individual Excel files
save_to_excel(df_reliance_cleaned, "df_reliance")
save_to_excel(df_tatasteel_cleaned, "df_tatasteel")
save_to_excel(df_infy_cleaned, "df_infy")

DataFrame 'df_reliance' successfully saved to Excel file: df_reliance_historical_1minute_data.xlsx
DataFrame 'df_tatasteel' successfully saved to Excel file: df_tatasteel_historical_1minute_data.xlsx
DataFrame 'df_infy' successfully saved to Excel file: df_infy_historical_1minute_data.xlsx

In [9]:
df_tatasteel_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47682 entries, 0 to 47681
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      47682 non-null  datetime64[ns, pytz.FixedOffset(330)]
 1   open           47682 non-null  float64
 2   high           47682 non-null  float64
 3   low            47682 non-null  float64
 4   close          47682 non-null  float64
 5   volume         47682 non-null  object
 6   open interest  47682 non-null  object
dtypes: datetime64[ns, pytz.FixedOffset(330)](1), float64(4), object(2)
memory usage: 2.5+ MB